CREATE TABLE `gate4games_stage`.`lvplayonlinux` ( `OXID` CHAR(32) NOT NULL , `LVAPPID` INT NOT NULL , `LVTITLE` VARCHAR(255) NOT NULL , `LVLASTUPDATE` DATETIME NOT NULL ) ENGINE = InnoDB;
ALTER TABLE `lvplayonlinux` ADD PRIMARY KEY(`OXID`);
ALTER TABLE `lvplayonlinux` ADD INDEX(`LVAPPID`);
ALTER TABLE `lvplayonlinux` ADD INDEX(`LVTITLE`);
