ALTER TABLE `oxvendor` ADD `LVMAINVENDOR` TINYINT NOT NULL DEFAULT '0' AFTER `OXSHOWSUFFIX`, ADD `LVSHORTCUT` VARCHAR(6) NOT NULL AFTER `LVMAINVENDOR`;

ALTER TABLE `oxmanufacturers` ADD `LVSHORTCUT` VARCHAR(6) NOT NULL AFTER `OXSHOWSUFFIX`;
